// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA11P05fL0i0n9j-2lRsqOoT8X_QgupQ78',
    appId: '1:646538415651:web:d595e17404dfc4c1636b96',
    messagingSenderId: '646538415651',
    projectId: 'ez-hub',
    authDomain: 'ez-hub.firebaseapp.com',
    storageBucket: 'ez-hub.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE1-e6VLx4YNvIDxdPAxYxDQSwP9OD8T0',
    appId: '1:646538415651:android:95ced3d0b60ae22b636b96',
    messagingSenderId: '646538415651',
    projectId: 'ez-hub',
    storageBucket: 'ez-hub.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_BPdPbps-vyxznwWhf_l3KK7W58bCiKI',
    appId: '1:646538415651:ios:e1e5425184914045636b96',
    messagingSenderId: '646538415651',
    projectId: 'ez-hub',
    storageBucket: 'ez-hub.appspot.com',
    iosBundleId: 'com.example.simone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_BPdPbps-vyxznwWhf_l3KK7W58bCiKI',
    appId: '1:646538415651:ios:e1e5425184914045636b96',
    messagingSenderId: '646538415651',
    projectId: 'ez-hub',
    storageBucket: 'ez-hub.appspot.com',
    iosBundleId: 'com.example.simone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA11P05fL0i0n9j-2lRsqOoT8X_QgupQ78',
    appId: '1:646538415651:web:67a1218c8566c368636b96',
    messagingSenderId: '646538415651',
    projectId: 'ez-hub',
    authDomain: 'ez-hub.firebaseapp.com',
    storageBucket: 'ez-hub.appspot.com',
  );
}
